kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nexus
spec:
  storageClassName: local
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /k8s/nexus
