apiVersion: v1
kind: Secret
metadata:
  name: secret-gitea
  namespace: ci
stringData:
  app.ini: |
    APP_NAME = Gitea
    RUN_USER = git
    RUN_MODE = prod

    [repository]
    ROOT = /data/git/repositories
    FORCE_PRIVATE = true
    DISABLE_HTTP_GIT = false

    [repository.upload]
    TEMP_PATH = /data/gitea/uploads

    [server]
    APP_DATA_PATH    = /data/gitea
    SSH_DOMAIN       = code.tozzi.fan
    DOMAIN           = code.tozzi.fan
    HTTP_PORT        = 3000
    ROOT_URL         = https://code.tozzi.fan/
    DISABLE_SSH      = true
    SSH_PORT         = 22
    LFS_START_SERVER = false
    OFFLINE_MODE     = false

    [database]
    DB_TYPE  = postgres
    PATH     = /data/gitea/gitea.db
    HOST     = postgres:5432
    NAME     = gitea
    USER     = gitea
    PASSWD   = gitea
    SSL_MODE = disable

    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    PROVIDER        = file

    [picture]
    AVATAR_UPLOAD_PATH      = /data/gitea/avatars
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = false

    [attachment]
    PATH = /data/gitea/attachments

    [log]
    ROOT_PATH = /data/gitea/log
    MODE      = file
    LEVEL     = Info

    [security]
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1MDY1MDU0MTF9.hH7Et0i1XWl7H8julJLGmsUk-2USFGQBJGXFJPaHU-E
    INSTALL_LOCK   = true
    SECRET_KEY     = fUs84U3Xq7

    [service]
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    DISABLE_REGISTRATION              = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    REQUIRE_SIGNIN_VIEW               = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = false
    NO_REPLY_ADDRESS                  = noreply.tozzi.fan

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

    [mailer]
    ENABLED       = false
    HOST          = smtp.tozzi.fan:465
    FROM          = noreply@tozzi.fan
    USER          = noreply
    PASSWD        = noreply

    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve
    REPO_INDEXER_ENABLED = true
    REPO_INDEXER_PATH = /data/gitea/indexers/repos.bleve
    UPDATE_BUFFER_LEN = 20
    MAX_FILE_SIZE = 8388608

    [cache]
    ADAPTER = memory
    INTERVAL = 60
    ITEM_TTL = 16h

    [webhook]
    QUEUE_LENGTH = 1000
    DELIVER_TIMEOUT = 5
    SKIP_TLS_VERIFY = true
    PAGING_NUM = 10
    
    [oauth2]
    ENABLE = false
