FROM nginx:1.16.1-alpine
COPY assets /usr/share/nginx/html/assets
COPY favicon.ico /usr/share/nginx/html/favicon.ico
COPY index.html /usr/share/nginx/html/index.html
COPY src /usr/share/nginx/html/src
